const config = {
  loginHeading: 'BrainIntelCorp',
  loginSubheading: 'Login to BrainIntelCorp',
  loginFooter:
    " By clicking 'Login' you agree to our Terms of Use. For further information about",
  continuedFooterNote:
    'how the system processes your personal data, please click on our ',
  loginPrivacyPOlicy: 'Privacy Policy',
  loginAccount: "Don't have an account?",
  loginContactUS: 'Register here',
  loginForgotPassword: 'Forgot Password?',
  loginRedirect: 'Back to Login',
  loginButton: 'Login',
  registrationButton: 'register',
  verifyButton: 'Verify',
  registrationHeading: 'New User Registrations',
  fogotPasswordHeading: 'Please enter your email and and press confirm',
  forgotPasswordButton: 'Confirm',
  resetHeading: 'Please enter the new password',
  resetPasswordNote:
    'Please enter the username or email that you have registered with',
  resetPasswordContinued:
    'us. You will receive a link to create a new password via email.',
  resetButton: 'Reset',
  resetBack: 'Back to login',
  instructions: 'Instructions have been sent',
  instrcutionsNote:
    'Password reset instructions have been sent to the email account',
  instructionsNoteCont: 'that you have registered with us.',
  resetPassowordInstructionNote:
    'Please note password must be at least 12 characters.',
  setupPassword: 'Set up new password',
  updateButton: 'Update Password',
  verification: 'Verification',
  verificationmail: 'Verification by Email',
  verificationsms: 'Verification by SMS',
  verificationAuthenticator: 'Verification by MS Authenticator Code',
  verificationSubheading:
    'To better protect your account, a step of verification is required. Please ',
  verificationSubheadingcont: 'choose one of the following option.',
  OTPnote:
    'Enter the code we sent to a****@informa.com. The code is valid for 30 minutes .',
  OTPSMSnote:
    'Enter the code we sent to +XXX*******XX. The code is valid for 30 minutes.',
  OTPAuthenticatorNote:
    'Open the Microsoft Authenticator app on your smartphone and enter the',
  OTPAuthenticatorNoteCont:
    ' one-time password code generated by app. Please note that each code',
  OTPAuthenticatorNoteContinued: 'valid for 30 seconds.',
  applyCode: 'Apply Code',
  otpresendmessage: 'Haven’t got the code? Resend code again.',
  otpresendmessagecont: 'Have issues? Try other verification options.',
  otpFooterNote:
    'If your email changed or in case of troubles, please contact xxx@xx.com',
  minutes: 'minutes',
  Back: 'Back',
  receiveSMS: 'Receive an SMS',
  receiveMail: 'Receive an Email',
  msAuthenticator: 'Сode in MS Authenticator',
  confirmationmessage:
    'We will send you an SMS to your mobile number +XXX*******XX with a confirmation code',
  confirmationmail:
    'We will send you an email to a****@informa.com with a confirmation code',
  confirmationAuth:
    'Open the Microsoft Authenticator app on your smartphone and enter the one-time password code',
  Help: 'Help',
};

export default config;
